"""Add user_id to memo

Revision ID: 766573d9862c
Revises: 
Create Date: 2025-05-09 16:13:36.787630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766573d9862c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memo', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('memo', 'content',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.create_foreign_key(None, 'memo', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memo', type_='foreignkey')
    op.alter_column('memo', 'content',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('memo', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('memo', 'user_id')
    # ### end Alembic commands ###
