"""Add kakao_id to User

Revision ID: cf6cc35efcb1
Revises: 744c12f172ff
Create Date: 2025-05-12 11:33:19.024791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf6cc35efcb1'
down_revision: Union[str, None] = '744c12f172ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kakao_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('naver_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_kakao_id'), 'users', ['kakao_id'], unique=True)
    op.create_index(op.f('ix_users_naver_id'), 'users', ['naver_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_naver_id'), table_name='users')
    op.drop_index(op.f('ix_users_kakao_id'), table_name='users')
    op.drop_column('users', 'naver_id')
    op.drop_column('users', 'kakao_id')
    # ### end Alembic commands ###
